eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      # 1. Configuración de CLIENTE (Necesaria para TokenRelay)
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ecommerce-realm
        registration:
          api-gateway-client:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: TOH2FNdbTDh76MatVvd2JwoQhD4N1dd5  # <--- ¡REEMPLAZA ESTO CON TU CÓDIGO!
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
      # 2. Configuración de SERVIDOR (Necesaria para validar entrada)
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm

    cloud:
      gateway:
        # 3. Filtro Global: Pasa el token a TODOS los microservicios
        default-filters:
          - TokenRelay

        routes:
          # Ruta a Microservicio de Productos
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/product/**

          # Ruta a Microservicio de Órdenes
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/order/**

          # Ruta a Microservicio de Inventario
          - id: inventory-service
            uri: lb://inventory-service
            predicates:
              - Path=/api/v1/inventory/**
# ✅ CONFIGURACIÓN DE OBSERVABILIDAD UNIFICADA (Traces, Logs y Metrics)
management:
  tracing:
    sampling:
      probability: 1.0  # Captura el 100% de las trazas para la prueba
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces # Endpoint HTTP OTLP
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs # Habilita el envío de logs a Grafana
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics # Habilita el envío de métricas a Grafana
  endpoints:
    web:
      exposure:
        include: "refresh, health, prometheus"

# ✅ CORRELACIÓN DE LOGS EN CONSOLA (Para ver el TraceID localmente)
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]" #

server:
  port: 9000
