eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082

logging:
  level:
    root: INFO
    com.ecommerce: INFO

# --- NUEVA CONFIGURACIÓN SMTP (Mailtrap) ---
spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: b59e1015031e12 # <--- Pega tu usuario aquí
    password: ****c3ee # <--- Pega tu password aquí
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
